spring.application.name=couponservice
server.port=8081

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

logging.level.root=INFO
logging.level.com.product=DEBUG
logging.level.com.cupon=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n